### ISSUE TITLE
[error] TypeError [ERR_INVALID_CALLBACK]: Callback must be a function

### ISSUE THREAD

**Issue by jejmule** [Autodesk/cam-posteditor#18]
Hello,
I am writting a custom post processor for Fusion 360, I am using visula studio code and the extension HSM
When I launch the post process, I heve the following error message.
Any idea how to solve that?
Thanks

[2019-10-30 17:00:01.817] [exthost] [error] TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
	at maybeCallback (fs.js:129:9)
	at exists (fs.js:197:3)
	at Object.fs.exists (ELECTRON_ASAR.js:408:27)
	at vscode.commands.registerCommand (c:\Users\jejmule\.vscode\extensions\autodesk.hsm-post-processor-2.1.0\out\src\extension.js:318:23)
	at v._executeContributedCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:518:753)
	at v._doExecuteCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:517:951)
	at v.executeCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:517:857)
	at Object.executeCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:692:410)
	at selectedCNCFile (c:\Users\jejmule\.vscode\extensions\autodesk.hsm-post-processor-2.1.0\out\src\extension.js:798:19)
	at vscode.window.showQuickPick.then.val (c:\Users\jejmule\.vscode\extensions\autodesk.hsm-post-processor-2.1.0\out\src\extension.js:782:60) HSM.postProcess

**Comment by george-roberts** [comment]
Hello,
Thanks for reporting the issue. Is this problem still happening in the latest version? I believe some updates we just made will fix this

**Comment by george-roberts** [comment]
Closing as no response
